/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef AGENTHTTPACCESS_H
#define AGENTHTTPACCESS_H

/*
 * function declarations 
 */
void            init_agentHttpAccess(void);

#endif                          /* AGENTHTTPACCESS_H */
