/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef AGENTHTTPADDRESS_H
#define AGENTHTTPADDRESS_H

/*
 * function declarations 
 */
void            	init_agentHttpAddress(void);

#endif                          /* AGENTHTTPADDRESS_H */
