/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 1.2 2002/07/17 14:41:53 dts12 Exp $
 */
#ifndef BUSYWORKERS_H
#define BUSYWORKERS_H

/*
 * function declarations 
 */
void            	init_busyWorkers(void);
Netsnmp_Node_Handler 	handler_busyWorkers;

#endif                          /* TOTALACCESS_H */
