/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef HTTPERROR405_H
#define HTTPERROR405_H

/*
 * function declarations 
 */
void            init_httpError405(void);
Netsnmp_Node_Handler handle_httpError405;

#endif                          /* HTTPERROR400_H */
