/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef HTTPERROR501_H
#define HTTPERROR501_H

/*
 * function declarations 
 */
void            init_httpError501(void);
Netsnmp_Node_Handler handle_httpError501;

#endif                          /* HTTPERROR501_H */
