/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef HTTPERROR400_H
#define HTTPERROR400_H

/*
 * function declarations 
 */
void            init_httpError400(void);
Netsnmp_Node_Handler handle_httpError400;

#endif                          /* HTTPERROR400_H */
