/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef HTTPERROR500_H
#define HTTPERROR500_H

/*
 * function declarations 
 */
void            init_httpError500(void);
Netsnmp_Node_Handler handle_httpError500;

#endif                          /* HTTPERROR500_H */
