/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 1.2 2002/07/17 14:41:53 dts12 Exp $
 */
#ifndef IDLEWORKERS_H
#define IDLEWORKERS_H

/*
 * function declarations 
 */
void            	init_idleWorkers(void);
Netsnmp_Node_Handler 	handler_idleWorkers;

#endif                          /* TOTALACCESS_H */
