/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef SERVERSTATUS_H
#define SERVERSTATUS_H

/*
 * function declarations 
 */
void            	init_serverStatus(void);
Netsnmp_Node_Handler 	handle_serverStatus;
int 			check_estado();
SNMPAlarmCallback send_status_notification;
void 			send_notification(int);	

#endif                          /* SERVERSTATUS_H */
