/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 1.2 2002/07/17 14:41:53 dts12 Exp $
 */
#ifndef SERVERKBYTESPERREQUEST_H
#define SERVERKBYTESPERREQUEST_H

/*
 * function declarations
 */
void            	init_serverKBytesPerRequest(void);
Netsnmp_Node_Handler 	handler_serverKBytesPerRequest;

#endif                          /* serverBytesPerRequest_H */
