/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 1.2 2002/07/17 14:41:53 dts12 Exp $
 */
#ifndef SERVERRESTART_H
#define SERVERRESTART_H

/*
 * function declarations 
 */
void            init_serverRestart(void);
Netsnmp_Node_Handler handle_serverRestart;
void		send_restart_notification();
#endif                          /* SERVERRESTART_H */
