/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 1.2 2002/07/17 14:41:53 dts12 Exp $
 */
#ifndef SERVERNAME_H
#define SERVERNAME_H

/*
 * function declarations 
 */
void            init_serverName(void);

#endif                          /* SERVERNAME_H */
