/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 1.2 2002/07/17 14:41:53 dts12 Exp $
 */
#ifndef SERVERTMPDIR_H
#define SERVERTMPDIR_H

/*
 * function declarations 
 */
void            init_serverTmpDir(void);

#endif                          /* SERVERROOT_H */
