/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef SERVERLISTENPORTS_H
#define SERVERLISTENPORTS_H

/*
 * function declarations 
 */
void            init_serverListenPorts(void);
void 		clean_table(void);
Netsnmp_Node_Handler 	serverListenPorts_handler;
#endif                          /* SERVERLISTENPORTS_H */
