/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 1.2 2002/07/17 14:41:53 dts12 Exp $
 */
#ifndef TOTALACCESS_H
#define TOTALACCESS_H

/*
 * function declarations 
 */
void            	init_totalAccess(void);
Netsnmp_Node_Handler 	handler_totalAccess;
int 			send_http_get(char*);

#endif                          /* TOTALACCESS_H */
