/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.7 2003/04/08 14:57:04 dts12 Exp $
 */
#ifndef TOTALSERVERPORTS_H
#define TOTALSERVERPORTS_H

/*
 * function declarations 
 */
void            	init_totalServerPorts(void);
Netsnmp_Node_Handler 	handle_totalServerPorts;

#endif                          /* TOTALSERVERPORTS_H */
