#!/bin/sh
PATH="/bin:/usr/bin:/usr/local/bin"
kbytes=`snmpget -OQv -c public -v1 localhost APACHE2-MIB::serverKBytesPerRequest.0`
bytes=`echo "$kbytes * 1024" | bc`
echo $bytes
echo $bytes
snmpget -OQv -c public -v1 localhost APACHE2-MIB::serverUptime.0
echo Apache Bytes per Request